services:
  - type: web
    name: scrape-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
